### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method closeSystemWindow on channel in.jvapps.system_alert_window)

### ISSUE THREAD

**Issue by nicolas-ducruet** [pvsvamsi/SystemAlertWindow#12]
I managed to :
- open the system alert window using your example
- Register the onclicks callbacks.

However when clicking on the simple button of your example window it triggers:

```
E/flutter (10888): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method closeSystemWindow on channel in.jvapps.system_alert_window)
E/flutter (10888): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (10888): <asynchronous suspension>
E/flutter (10888): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (10888): #2      SystemAlertWindow.closeSystemWindow (package:system_alert_window/system_alert_window.dart:114:27)
```

I am running it on AndroidX (API 29)

**Comment by nicolas-ducruet** [comment]
I fixed it, it was an incompatibility with the flutter location package v 3.0.2

**Comment by pvsvamsi** [comment]
Closing this issue
