### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method closeSystemWindow on channel in.jvapps.system_alert_window)

### ISSUE THREAD

**Issue by ruixue521** [pvsvamsi/SystemAlertWindow#31]
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method closeSystemWindow on channel in.jvapps.system_alert_window)

**Comment by ruixue521** [comment]
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method closeSystemWindow on channel in.jvapps.system_alert_window)
E/flutter (17135): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (17135): <asynchronous suspension>
E/flutter (17135): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (17135): #2      SystemAlertWindow.closeSystemWindow (package:system_alert_window/system_alert_window.dart:114:27)
E/flutter (17135): #3      callBack (package:landbridge_mobile/main.dart:257:25)
E/flutter (17135): #4      callbackDispatcher.<anonymous closure> (package:system_alert_window/system_alert_window.dart:136:15)
E/flutter (17135): #5      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:409:55)
E/flutter (17135): #6      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:377:54)
E/flutter (17135): #7      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:199:33)
E/flutter (17135): #8      _invoke3.<anonymous closure> (dart:ui/hooks.dart:290:15)
E/flutter (17135): #9      _rootRun (dart:async/zone.dart:1184:13)
E/flutter (17135): #10     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (17135): #11     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (17135): #12     _invoke3 (dart:ui/hooks.dart:289:10)
E/flutter (17135): #13     _dispatchPlatformMessage (dart:ui/hooks.dart:164:5)

**Comment by ruixue521** [comment]
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method closeSystemWindow on channel in.jvapps.system_alert_window)
E/flutter (17135): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (17135): <asynchronous suspension>
E/flutter (17135): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (17135): #2      SystemAlertWindow.closeSystemWindow (package:system_alert_window/system_alert_window.dart:114:27)
E/flutter (17135): #3      callBack (package:landbridge_mobile/main.dart:257:25)
E/flutter (17135): #4      callbackDispatcher.<anonymous closure> (package:system_alert_window/system_alert_window.dart:136:15)
E/flutter (17135): #5      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:409:55)
E/flutter (17135): #6      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:377:54)
E/flutter (17135): #7      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:199:33)
E/flutter (17135): #8      _invoke3.<anonymous closure> (dart:ui/hooks.dart:290:15)
E/flutter (17135): #9      _rootRun (dart:async/zone.dart:1184:13)
E/flutter (17135): #10     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (17135): #11     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (17135): #12     _invoke3 (dart:ui/hooks.dart:289:10)
E/flutter (17135): #13     _dispatchPlatformMessage (dart:ui/hooks.dart:164:5)

**Comment by ruixue521** [comment]
Ok in demo, not in my project

**Comment by pvsvamsi** [comment]
@ruixue521 Did you follow [this section](https://github.com/pvsvamsi/SystemAlertWindow#application-class) in readme?
